import { chromium } from '/Users/admin/Claude/ttc-servsafe-study-main/node_modules/playwright/index.mjs';
const USER={userId:'k17e9kk2wxe3rbarp11j4rtdyn80w5pp',gamerName:'rerun',displayName:'Rerun',firstName:'leland'};
const b=await chromium.launch();const p=await b.newPage({viewport:{width:1180,height:1000}});
await p.addInitScript(u=>{localStorage.setItem('chefKitchenUser',JSON.stringify(u));localStorage.setItem('chefKitchenPersonalDevice','true');localStorage.setItem('chefKitchenLastActive',Date.now().toString());},USER);
p.on('pageerror',e=>console.log('PAGEERROR:',e.message));
await p.goto('http://localhost:8123/index.html');
await p.waitForTimeout(3000);
console.log('pop-frame count:',await p.locator('.pop-frame').count());
console.log('popper count:',await p.locator('.popper').count());
console.log('skin:',await p.evaluate(()=>localStorage.getItem('chefKitchenSkin')));
console.log('body len:',(await p.evaluate(()=>document.body.innerText)).length);
await b.close();
