// CUL-112: Classical Cooking Foundations (Trident Technical College)
// Quiz questions (IDs 3001+) and flashcards (IDs 4001+)
// Real quiz questions are marked examFocus:true with "chapter" doubling as the quiz number
// so the hybrid quiz-group filter works (Quiz 1 -> chapter 1, Quiz 2 -> chapter 2, etc.).
// All real-quiz answers verified against the student's 100% submissions.
//   Quiz 1 "Stocks & Sauces"      (IDs 3001-3025, chapter:1) - Quiz - 1b.pdf
//   Quiz 2 "Poultry"              (IDs 3050-3074, chapter:2) - Quiz - 2.pdf
//   Quiz 4 "Fish and Shellfish"   (IDs 3075-3094, chapter:4) - Quiz - 3.pdf (D2L titles it "Q4")
//   (Quiz 3 not yet taken/provided - gap is intentional)
// Supplementary study questions (IDs 3026-3049): chapter:null, examFocus:false (from PowerPoints)
// Flashcards (IDs 4001+): Classical Cooking vocabulary (VOCABULARY.pdf)
var questionsCUL112 = [
  // ===== QUIZ 1: STOCKS & SAUCES (verified) =====
  {
    id: 3001,
    question: "What is a roux and what is it used for?",
    options: [
      "Leading sauce",
      "A light sauce or broth usually served with fish or shellfish",
      "A base used for flavoring a stock or sauce",
      "Equal parts, by weight, of flour and fat cooked to be used to thicken"
    ],
    correct: 3,
    hint: "It is a cooked flour-and-fat mixture.",
    explanation: "A roux is equal parts (by weight) flour and fat cooked together and used as a thickening agent for sauces and soups.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3002,
    question: "When starting a stock, all ingredients should be covered with cold water because:",
    options: [
      "blood and impurities are dissolved which keeps the stock clear.",
      "the stock may spoil before reaching proper simmering temperature.",
      "hot water may change the simmering temperature of white stock.",
      "hot water will make the stock too clear for bouillon."
    ],
    correct: 0,
    hint: "Cold water helps draw out and dissolve impurities.",
    explanation: "Starting in cold water dissolves blood and impurities so they can be skimmed off, keeping the finished stock clear.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3003,
    question: "Which of the following statements is true about fish stock ingredients?",
    options: [
      "All stocks derive their flavor from bones.",
      "Bones from lean white fish make the best fish stock.",
      "Fumet is a flavorful veal stock often made with wine.",
      "The color of a brown stock comes from a well cooked roux."
    ],
    correct: 1,
    hint: "Think about which fish give a clean, mild stock.",
    explanation: "Lean white fish bones make the best fish stock. (Fumet is a fish stock, and a brown stock's color comes from browned bones and mirepoix, not roux.)",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3004,
    question: "When making a stock, the size into which the mirepoix is chopped determines:",
    options: [
      "the stock's cooking time",
      "the amount of stock being made",
      "the type of stock being made",
      "the type of seasoning used to make the stock"
    ],
    correct: 0,
    hint: "Smaller pieces release flavor faster.",
    explanation: "The mirepoix is cut to match the cooking time of the stock — smaller for short cooks (fish), larger for long cooks (beef/veal).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3005,
    question: "What soup is described as a hearty soup with chunks of the main ingredient, which always includes diced potatoes and most times contains cream or milk, and garnishes?",
    options: ["Puree soups", "Bisques", "Consomme soups", "Chowders"],
    correct: 3,
    hint: "Think New England seafood soup with potatoes.",
    explanation: "Chowders are hearty, chunky soups that always include diced potatoes and usually cream or milk.",
    category: "Soups",
    topic: "Soups",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3006,
    question: "Which sauce below does NOT belong to the small tomato sauce family?",
    options: ["Creole sauce", "Béarnaise sauce", "Spanish sauce", "Milanese sauce"],
    correct: 1,
    hint: "One of these is a derivative of Hollandaise.",
    explanation: "Béarnaise is a derivative of Hollandaise, not Tomato. Creole, Spanish, and Milanese are tomato-sauce derivatives.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3007,
    question: "Which sauce below does NOT belong to the Béchamel sauce family?",
    options: ["Tomato sauce", "Mornay sauce", "Nantua sauce", "Cheese sauce"],
    correct: 0,
    hint: "One of these is itself a mother sauce.",
    explanation: "Tomato sauce is its own mother sauce. Mornay, Nantua, and Cheese sauce are all derivatives of Béchamel.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3008,
    question: "The standard proportions of ingredients in mirepoix are _________.",
    options: [
      "50% onions, 25% celery, and 25% carrots",
      "25% onions, 50% celery, and 25% carrots",
      "25% onions, 25% celery, and 50% carrots",
      "mirepoix does not contain carrots, onions and celery"
    ],
    correct: 0,
    hint: "Onions make up half.",
    explanation: "Standard mirepoix is 50% onion, 25% carrot, and 25% celery by weight.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3009,
    question: "What is the main ingredient in commercial bases?",
    options: ["the flavor that it represents", "sodium", "Extracts", "mirepoix and seasonings"],
    correct: 1,
    hint: "It is a major reason they are used sparingly.",
    explanation: "The main ingredient in most commercial bases is sodium (salt).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3010,
    question: "What soup is made from a stock or broth that has been clarified to remove impurities so that it is crystal clear?",
    options: ["Bisque soups", "Cream soups", "Consomme soups", "Puree soups"],
    correct: 2,
    hint: "It is the clearest of the clear soups.",
    explanation: "A consommé is a clarified stock or broth that is crystal clear.",
    category: "Soups",
    topic: "Soups",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3011,
    question: "What is the most important ingredient in most, but not all, stocks?",
    options: ["Vegetables", "Seasonings", "Bones", "Liquid"],
    correct: 2,
    hint: "They provide gelatin, flavor, and body.",
    explanation: "Bones are the most important ingredient in most stocks (vegetable stock being the exception).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3012,
    question: "What is the French word for \"stock\" or \"base\"?",
    options: ["Mirepoix", "Gelatin", "Fond", "Matignon"],
    correct: 2,
    hint: "It is also the word for the browned bits left in a pan.",
    explanation: "\"Fond\" is the French word for stock or base (and also the flavorful browned bits in a pan).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3013,
    question: "What is the term for cooking over low heat without browning?",
    options: ["Nagé", "Glaze", "Court bouillon", "Sweat"],
    correct: 3,
    hint: "You want to soften, not color, the vegetables.",
    explanation: "To \"sweat\" is to cook over low heat to soften without browning.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3014,
    question: "What term means to swirl or stir a liquid in a sauté pan to dissolve cooked food particles remaining on the bottom, often used to make a base or sauce?",
    options: ["Nagé", "Deglaze", "Remoulagé", "Sweat"],
    correct: 1,
    hint: "You are dissolving the fond.",
    explanation: "Deglazing adds liquid to dissolve the fond (browned bits) so it can flavor a sauce.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3015,
    question: "The proper way to achieve a brown stock is to:",
    options: [
      "wash the bones thoroughly before simmering in water",
      "caramelize the bones before simmering in water",
      "use only veal bones to make the stock",
      "use a limited amount of mirepoix to achieve an amber color"
    ],
    correct: 1,
    hint: "Color comes from browning, not the liquid.",
    explanation: "Brown stock gets its color and deep flavor from caramelizing (roasting) the bones and mirepoix before simmering.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3016,
    question: "What is the term for the foundation for the entire classic repertoire of hot sauces?",
    options: ["Mother sauces", "Compound sauces", "Small sauces", "Supreme sauces"],
    correct: 0,
    hint: "There are five of them.",
    explanation: "The five mother sauces (Béchamel, Velouté, Espagnole, Tomato, Hollandaise) are the foundation of classic hot sauces.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3017,
    question: "What poaching liquid is made by simmering vegetables and seasonings in water with an acidic liquid such as vinegar or wine added?",
    options: ["fumet", "gelatin", "court bouillon", "glaze"],
    correct: 2,
    hint: "French for \"short broth.\"",
    explanation: "Court bouillon is an aromatic, acidulated vegetable broth used for poaching.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3018,
    question: "Most stocks are made from:",
    options: [
      "Bones, vegetables, seasonings, and liquids",
      "Vegetables, bases, seasonings, and water",
      "Bones, bases, seasoning, and water",
      "Vegetables, mirepoix, fond, bones"
    ],
    correct: 0,
    hint: "Think of the four essential parts of a stock.",
    explanation: "The four essential parts of a stock are a major flavoring (bones), mirepoix (vegetables), liquid, and aromatics (seasonings).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3019,
    question: "White chicken stock should be simmered for a minimum of?",
    options: ["30 to 60 minutes.", "1 to 2 hours.", "3 to 4 hours.", "6 to 8 hours."],
    correct: 2,
    hint: "Less than beef/veal (6-8 hrs), more than fish.",
    explanation: "Chicken stock simmers about 3 to 4 hours (beef/veal 6-8 hours; fish only 30-45 minutes).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3020,
    question: "Some of the herbs most frequently used in a sachet for stocks include:",
    options: [
      "Thyme, parsley, bay leaf.",
      "Parsley, basil, sachet.",
      "Thyme, tarragon, bay leaf.",
      "Sage, cloves, peppercorns."
    ],
    correct: 0,
    hint: "Classic sachet d'épices aromatics.",
    explanation: "A standard sachet for stock typically holds thyme, parsley stems, and a bay leaf (plus peppercorns).",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3021,
    question: "What type of soups are generally made from starchy vegetables or legumes that are simmered in liquid and a portion placed into a food processor for completion?",
    options: ["Bisques soups", "Puree soups", "Chowder soups", "Thick soups"],
    correct: 1,
    hint: "The main ingredient itself does the thickening.",
    explanation: "Purée soups are thickened by puréeing their main ingredient (often starchy vegetables or legumes).",
    category: "Soups",
    topic: "Soups",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3022,
    question: "What is the main purpose of a raft when making clear soups?",
    options: ["Clarifying the soup", "Enriching the soup", "Fortify the soup", "Garnishing the soup"],
    correct: 0,
    hint: "It traps impurities at the surface.",
    explanation: "The raft, formed by the clearmeat rising to the top, clarifies a consommé by trapping impurities.",
    category: "Soups",
    topic: "Soups",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3023,
    question: "Which mother sauce is the only emulsified sauce listed?",
    options: ["Hollandaise", "Veloute", "Béchamel", "Espagnole"],
    correct: 0,
    hint: "It is an emulsion of egg yolks and butter.",
    explanation: "Hollandaise is an emulsified mother sauce (egg yolks, butter, lemon). The others are roux-thickened.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3024,
    question: "A stock should be brought to a boil and then allowed to boil throughout the cooking process.",
    options: ["Yes", "No", "No, it is then reduced to a simmer", "Cook at 125 degrees F"],
    correct: 2,
    hint: "Boiling makes a stock cloudy.",
    explanation: "A stock is brought up to a boil then reduced to a gentle simmer; boiling throughout would make it cloudy and greasy.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3025,
    question: "What thick glace is made by reducing by half equal parts of brown sauce and brown stock and is usually finished with a small amount of Madeira or Sherry wine?",
    options: ["Espagnole", "Bercy", "Supreme sauce", "Demi-glace"],
    correct: 3,
    hint: "It is a rich derivative of Espagnole.",
    explanation: "Demi-glace is made by reducing equal parts Espagnole (brown sauce) and brown stock by half, often finished with Madeira or Sherry.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: 1,
    examFocus: true,
    type: "quiz"
  },

  // ===== SUPPLEMENTARY STUDY QUESTIONS (from PowerPoints; not on Quiz 1) =====
  {
    id: 3026,
    question: "What is the standard ratio of mirepoix to liquid when making stock?",
    options: ["1 lb mirepoix : 1 gallon liquid", "1 lb mirepoix : 1 quart liquid", "2 lb mirepoix : 1 gallon liquid", "1 lb mirepoix : 5 gallons liquid"],
    correct: 0,
    hint: "One pound per gallon.",
    explanation: "The standard ratio is 1 pound of mirepoix per gallon of liquid.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3027,
    question: "How does a white mirepoix differ from a standard mirepoix?",
    options: [
      "It replaces carrots with parsnips and adds mushrooms and leeks",
      "It removes the onions",
      "It uses only carrots and celery",
      "It adds tomato product"
    ],
    correct: 0,
    hint: "Remove the orange color; add pale aromatics.",
    explanation: "White mirepoix replaces carrots with parsnips and adds mushrooms and leeks, keeping a light color for white stocks and sauces.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3028,
    question: "Which stock is made from browned bones and browned mirepoix?",
    options: ["White stock", "Brown stock", "Fumet", "Court bouillon"],
    correct: 1,
    hint: "Color comes from caramelization.",
    explanation: "A brown stock is made from bones and mirepoix that have been browned (caramelized) first.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3029,
    question: "What is a fumet?",
    options: ["A vegetable broth for poaching", "A fish stock made from fish bones and white wine", "A reduced brown stock", "A clarified consommé"],
    correct: 1,
    hint: "It is a type of fish stock.",
    explanation: "A fumet is a fish stock made from fish bones with white wine added.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3030,
    question: "What is a glace?",
    options: ["A reduced stock used to flavor sauces", "A type of mirepoix", "An emulsified sauce", "A clear soup"],
    correct: 0,
    hint: "Reduce a stock dramatically.",
    explanation: "A glace is a stock that has been dramatically reduced and is used to flavor sauces.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3031,
    question: "What are the four essential parts of a stock?",
    options: [
      "Bones, mirepoix, liquid, and aromatics",
      "Bones, roux, water, and salt",
      "Vegetables, bases, seasonings, and water",
      "Mirepoix, fond, gelatin, and wine"
    ],
    correct: 0,
    hint: "Flavoring, vegetables, liquid, seasoning.",
    explanation: "The four essential parts of a stock are the major flavoring (bones), mirepoix, liquid (usually water), and aromatics.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3032,
    question: "Why is cartilage valued when making stock?",
    options: ["It produces the best gelatin", "It adds color", "It clarifies the stock", "It speeds up cooking"],
    correct: 0,
    hint: "Think about body and mouthfeel.",
    explanation: "Cartilage produces the best gelatin, which gives a stock body.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3033,
    question: "Approximately how long is a fish stock simmered?",
    options: ["30 to 45 minutes", "3 to 4 hours", "6 to 8 hours", "12 hours"],
    correct: 0,
    hint: "Much shorter than meat stocks.",
    explanation: "Fish stock simmers only about 30 to 45 minutes; longer cooking makes it bitter.",
    category: "Stocks & Sauces",
    topic: "Stocks",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3034,
    question: "Which mother sauce is made from milk thickened with a white roux?",
    options: ["Velouté", "Béchamel", "Espagnole", "Tomato"],
    correct: 1,
    hint: "It is the dairy-based mother sauce.",
    explanation: "Béchamel is made from milk thickened with a white roux.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3035,
    question: "Which mother sauce is made from white stock thickened with a blond roux?",
    options: ["Béchamel", "Velouté", "Espagnole", "Hollandaise"],
    correct: 1,
    hint: "Stock plus a lightly cooked roux.",
    explanation: "Velouté is made from white stock thickened with a blond roux.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3036,
    question: "Which thickening agent is made from equal parts soft butter and flour kneaded together?",
    options: ["Slurry", "Roux", "Beurre manié", "Liaison"],
    correct: 2,
    hint: "\"Kneaded butter\" in French.",
    explanation: "Beurre manié is equal parts soft (raw) butter and flour kneaded together, whisked in to thicken at the end of cooking.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3037,
    question: "What is a liaison?",
    options: ["A mixture of egg yolks and cream used to enrich and thicken", "Cornstarch and cold water", "Equal parts flour and fat", "A reduced stock"],
    correct: 0,
    hint: "It enriches as well as thickens.",
    explanation: "A liaison is a mixture of egg yolks and cream used to enrich and lightly thicken a sauce or soup.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3038,
    question: "A slurry is made from:",
    options: ["Cornstarch and cold liquid", "Butter and flour", "Egg yolks and cream", "Flour and hot fat"],
    correct: 0,
    hint: "Starch must be mixed with cold liquid first.",
    explanation: "A slurry is a starch (such as cornstarch) mixed with a cold liquid before being added to thicken.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3039,
    question: "Which type of roux is cooked the longest and used for Espagnole?",
    options: ["White roux", "Blond roux", "Brown roux", "Red roux"],
    correct: 2,
    hint: "Darkest color, deepest flavor, least thickening power.",
    explanation: "Brown roux is cooked until brown and is used for Espagnole (brown sauce).",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3040,
    question: "Mornay sauce is a small (compound) sauce derived from which mother sauce?",
    options: ["Béchamel", "Velouté", "Espagnole", "Tomato"],
    correct: 0,
    hint: "Add cheese to a milk-based sauce.",
    explanation: "Mornay (a cheese sauce) is a derivative of Béchamel.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3041,
    question: "What does the term \"nappé\" describe?",
    options: ["The consistency of a sauce that coats the back of a spoon", "Finishing a sauce with butter", "A clarified stock", "A reduced glaze"],
    correct: 0,
    hint: "It is about coating consistency.",
    explanation: "Nappé describes a sauce thick enough to coat the back of a spoon.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3042,
    question: "What does \"monter au beurre\" mean?",
    options: ["Finishing a sauce with butter", "Browning bones for stock", "Clarifying a consommé", "Making a roux"],
    correct: 0,
    hint: "It happens at the very end, for shine and richness.",
    explanation: "Monter au beurre means to finish a sauce by whisking in cold butter for richness and sheen.",
    category: "Stocks & Sauces",
    topic: "Sauces",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3043,
    question: "What are the two main categories of soups?",
    options: ["Clear and thick", "Hot and cold", "Cream and purée", "Broth and bisque"],
    correct: 0,
    hint: "Think about whether you can see through it.",
    explanation: "Soups fall into two main categories: clear soups and thick soups.",
    category: "Soups",
    topic: "Soups",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3044,
    question: "A bisque is best described as:",
    options: ["A cream soup made from shellfish", "A clarified clear soup", "A chunky potato soup", "A clear vegetable broth"],
    correct: 0,
    hint: "Think lobster or crab.",
    explanation: "A bisque is a thick cream soup traditionally made from shellfish.",
    category: "Soups",
    topic: "Soups",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3045,
    question: "What is a clearmeat (clarification mixture) typically made of?",
    options: [
      "Ground meat, egg whites, mirepoix, acid, and tomato",
      "Flour, fat, and stock",
      "Egg yolks and cream",
      "Butter, flour, and milk"
    ],
    correct: 0,
    hint: "Egg whites are the key clarifying agent.",
    explanation: "A clearmeat combines ground meat, egg whites, mirepoix, an acid, and tomato; it forms the raft that clarifies a consommé.",
    category: "Soups",
    topic: "Soups",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3046,
    question: "At what temperature should hot soups be held for service?",
    options: ["Above 140°F", "Above 110°F", "Above 165°F", "Above 200°F"],
    correct: 0,
    hint: "Same as the hot-holding food safety standard.",
    explanation: "Hot soups should be served/held above 140°F; cold soups below 40°F.",
    category: "Soups",
    topic: "Soups",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3047,
    question: "By which method is heat transferred directly through physical contact, such as a pot on a burner?",
    options: ["Conduction", "Convection", "Radiation", "Induction"],
    correct: 0,
    hint: "Direct contact, transferring from one object to another.",
    explanation: "Conduction transfers heat through direct contact (e.g., burner to pan to food).",
    category: "Cooking Methods & Principles",
    topic: "Cooking Principles",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3048,
    question: "Which method transfers heat through the movement of air, liquid, or steam?",
    options: ["Conduction", "Convection", "Radiation", "Searing"],
    correct: 1,
    hint: "Think of a fan oven circulating air.",
    explanation: "Convection transfers heat through moving fluids (air, liquid, or steam); it can be natural or mechanical.",
    category: "Cooking Methods & Principles",
    topic: "Cooking Principles",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },
  {
    id: 3049,
    question: "When food is heated, which of the following correctly describes an effect of heat?",
    options: [
      "Proteins coagulate, starches gelatinize, and sugars caramelize",
      "Proteins gelatinize and sugars evaporate",
      "Starches caramelize and proteins dissolve",
      "Water coagulates and fats gelatinize"
    ],
    correct: 0,
    hint: "Each component reacts differently to heat.",
    explanation: "Heat causes proteins to coagulate, starches to gelatinize, sugars to caramelize, water to evaporate, and fats to melt.",
    category: "Cooking Methods & Principles",
    topic: "Cooking Principles",
    chapter: null,
    examFocus: false,
    type: "quiz"
  },

  // ===== QUIZ 2: POULTRY (verified, Quiz - 2.pdf, 100%) =====
  {
    id: 3050,
    question: "A guinea hen is a __________.",
    options: ["domesticated descendant of a game bird", "castrated chicken", "Rock Cornish game hen", "a child's pet"],
    correct: 0,
    hint: "It started out wild.",
    explanation: "A guinea hen is a domesticated descendant of a game bird.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3051,
    question: "The least preferable way to determine the doneness of a small bird is to ____.",
    options: ["test for looseness of joints", "observe the juices inside the cavity", "check for flesh separating from the bone", "pierce deeply with a fork and twist the flesh"],
    correct: 3,
    hint: "One method pierces the bird and lets juices escape.",
    explanation: "Piercing deeply with a fork and twisting the flesh is the least preferable method — it lets juices escape and damages the bird.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3052,
    question: "What technique is used for tying a whole bird to keep its shape for roasting?",
    options: ["Barding", "Frenching", "Trussing", "Poêle"],
    correct: 2,
    hint: "It uses butcher's twine.",
    explanation: "Trussing is tying a whole bird with twine so it holds its shape and cooks evenly during roasting.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3053,
    question: "Free-range chickens' __________.",
    options: ["eat outdoors and are not caged", "are allowed to move around freely", "are raised in a more \"natural\" environment than non-free-range chickens", "all of the above"],
    correct: 3,
    hint: "Consider every option together.",
    explanation: "Free-range chickens are uncaged, allowed to move freely, and raised in a more natural environment — all of the above.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3054,
    question: "When storing poultry it is critical that it is stored on ice and kept at _______.",
    options: ["32-34 degrees", "30-32 degrees", "34-36 degrees", "Frozen only"],
    correct: 0,
    hint: "Just above freezing.",
    explanation: "Fresh poultry should be stored on ice at 32-34°F.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3055,
    question: "Foie Gras is the enlarged or fattened liver of a ________.",
    options: ["Duck/Goose", "Squab/Pheasant", "Guinea/Partridge", "Emu/Rhea"],
    correct: 0,
    hint: "A French delicacy from waterfowl.",
    explanation: "Foie gras is the fattened liver of a duck or goose.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3056,
    question: "A capon is a ________.",
    options: ["Squab", "Young pigeon", "Young turkey", "Castrated male chicken"],
    correct: 3,
    hint: "A specially raised male bird.",
    explanation: "A capon is a castrated male chicken, prized for tender, flavorful meat.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3057,
    question: "When ordering poultry, W.O.G. is referred to as?",
    options: ["With out Gross Weight", "With out Gravy", "With Giblets", "With out Giblets"],
    correct: 3,
    hint: "G is for giblets.",
    explanation: "W.O.G. stands for \"Without Giblets.\"",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3058,
    question: "A Ratite is a family of flightless birds that include _________.",
    options: ["Pigeon, turkey, and capon", "Ostrich, squab, and quail", "Rhea, mousse, and ostrich", "Emu, Ostrich, and Rhea"],
    correct: 3,
    hint: "All three are large flightless birds.",
    explanation: "Ratites are flightless birds — the emu, ostrich, and rhea.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3059,
    question: "An airline breast is also known as a _________ breast and should contain the wing drumette.",
    options: ["Wingy", "Supreme", "Frenched", "American"],
    correct: 1,
    hint: "Also the name of a velouté derivative.",
    explanation: "An airline breast is also called a supreme — a breast with the first wing joint (drumette) attached.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3060,
    question: "The shape of the carcass; amount of flesh; amount of fat; presence or absence of pinfeathers; skin tears, cuts, or broken bones; and blemishes or bruises are the basis for the _____ of poultry.",
    options: ["grading", "inspection", "classification", "all of the above"],
    correct: 3,
    hint: "These factors feed into more than one thing.",
    explanation: "Those quality factors form the basis for grading, inspection, and classification of poultry — all of the above.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3061,
    question: "A young pigeon is commercially known as?",
    options: ["Squab", "Poussin", "Ratite", "Rhea"],
    correct: 0,
    hint: "A small, tender bird served whole.",
    explanation: "A young pigeon is commercially known as a squab.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3062,
    question: "Poultry is known for its long shelf life and being a non-hazardous food.",
    options: ["True", "False"],
    correct: 1,
    hint: "Poultry is a TCS/PHF food.",
    explanation: "False — poultry is highly perishable and a potentially hazardous (TCS) food requiring careful temperature control.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3063,
    question: "Duck and goose are low in fat.",
    options: ["True", "False"],
    correct: 1,
    hint: "Think about their rich, fatty meat.",
    explanation: "False — duck and goose are high in fat compared with chicken and turkey.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3064,
    question: "When cutting an 8-way chicken, the first cut should always be the backbone?",
    options: ["True", "False"],
    correct: 1,
    hint: "The legs come off first.",
    explanation: "False — when fabricating an 8-way cut chicken, the backbone is not the first cut.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3065,
    question: "How is poultry graded by the USDA?",
    options: ["USDA 1,2,3", "Choice, Select, Commercial", "USDA A, B, C", "Prime, Choice, Good"],
    correct: 2,
    hint: "It uses letters.",
    explanation: "Poultry is graded USDA A, B, and C.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3066,
    question: "What are the five classes of chicken?",
    options: ["Roaster, Broiler, Fryer, Fowl, Foie Gras", "Fowl, Stewing hen, Broiler, Fryer, Ratites", "Game hen, Broiler/fryer, Roaster, Capon, Stewing hen", "Broiler, Fryer, Roaster, Stewing hen, Guinea hen"],
    correct: 2,
    hint: "Ranges from smallest (game hen) to oldest (stewing hen).",
    explanation: "The five classes of chicken are game hen, broiler/fryer, roaster, capon, and stewing hen.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3067,
    question: "Which one of these birds has only dark meat?",
    options: ["Duck", "Goose", "Squab", "All of the above", "None of the above"],
    correct: 3,
    hint: "These are all migratory/active flyers.",
    explanation: "Duck, goose, and squab all have only dark meat — all of the above.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3068,
    question: "All poultry is inspected by the ________?",
    options: ["Dehec", "USDA", "Dept. of Agriculture", "Each of the above"],
    correct: 1,
    hint: "The same agency that grades it.",
    explanation: "All poultry is inspected by the USDA. Inspection is mandatory.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3069,
    question: "Which color meat contains more niacin and riboflavin than the other?",
    options: ["Dark meat", "White meat"],
    correct: 0,
    hint: "The more active muscles.",
    explanation: "Dark meat contains more niacin and riboflavin than white meat.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3070,
    question: "The internal temperature of a chicken should reach _______ before serving.",
    options: ["165", "155", "145", "180"],
    correct: 0,
    hint: "The standard poultry safe temperature.",
    explanation: "Chicken should reach an internal temperature of 165°F before serving.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3071,
    question: "List the three grades of poultry.",
    options: ["1,2,3 and 4", "A,B,C", "A1,A2,A3", "None of the above"],
    correct: 1,
    hint: "Letters, not numbers.",
    explanation: "The three grades of poultry are A, B, and C.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3072,
    question: "Poultry should be cooked to 155 degrees?",
    options: ["True", "False"],
    correct: 1,
    hint: "Poultry needs a higher temp than that.",
    explanation: "False — poultry must be cooked to 165°F, not 155°F.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3073,
    question: "A Poussin is also known as a __________.",
    options: ["duck", "pigeon", "turkey", "small chicken/game hen"],
    correct: 3,
    hint: "A very young, small bird.",
    explanation: "A poussin is a young, small chicken — also known as a game hen.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3074,
    question: "Which grades of poultry are primarily used for processed poultry products?",
    options: ["A, B, C", "B & C", "A & B", "None of the above"],
    correct: 1,
    hint: "The lower two grades.",
    explanation: "Grades B and C are used primarily for processed poultry products; Grade A is for retail/whole birds.",
    category: "Poultry",
    topic: "Poultry",
    chapter: 2,
    examFocus: true,
    type: "quiz"
  },

  // ===== QUIZ 4: FISH AND SHELLFISH (verified, Quiz - 3.pdf / D2L "Q4", 100%) =====
  {
    id: 3075,
    question: "Clams, oysters and mussels should be stored under what conditions?",
    options: ["at room temperature", "In ice water", "41 degrees and high humidity", "41 degrees and low humidity"],
    correct: 2,
    hint: "Live shellfish need to stay cold and moist.",
    explanation: "Live clams, oysters, and mussels should be stored at 41°F and high humidity so they stay alive.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3076,
    question: "An example of a univalve is a:",
    options: ["Oyster", "Mussel", "clam", "Abalone"],
    correct: 3,
    hint: "A single-shelled mollusk.",
    explanation: "An abalone is a univalve (single shell); oysters, mussels, and clams are bivalves.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3077,
    question: "Flat fish differ from round fish primarily in the fact that their ________ are located differently?",
    options: ["Dorsal fin", "Pectorial fin", "Gill", "Eyes"],
    correct: 3,
    hint: "Both are on the same side in a flatfish.",
    explanation: "Flatfish (like flounder) have both eyes on the same (top) side, unlike round fish.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3078,
    question: "What is the most common mistake when cooking seafood?",
    options: ["Overcooking", "Over seasoning", "using rancid oil", "Under cooking"],
    correct: 0,
    hint: "Seafood cooks fast and dries out.",
    explanation: "Overcooking is the most common mistake — seafood is delicate and cooks quickly.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3079,
    question: "A salmon would be considered an oily fish?",
    options: ["True", "False"],
    correct: 0,
    hint: "Think about its high omega-3 content.",
    explanation: "True — salmon is an oily (fatty) fish.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3080,
    question: "A drawn fish is one that has had:",
    options: ["Scales removed", "nothing removed", "Viscera removed", "Head removed"],
    correct: 2,
    hint: "Only the guts are taken out.",
    explanation: "A drawn fish has had only its viscera (guts) removed.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3081,
    question: "Grouper would be considered a mild, flaky white fish?",
    options: ["True", "False"],
    correct: 0,
    hint: "It's a classic lean white fish.",
    explanation: "True — grouper is a mild, flaky white fish.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3082,
    question: "Fish and shellfish inspections are:",
    options: ["only from private fishermen", "only for imported produce", "Mandatory", "Voluntary"],
    correct: 3,
    hint: "Unlike poultry, this isn't required.",
    explanation: "Fish and shellfish inspection by the FDA/NOAA is voluntary, not mandatory.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3083,
    question: "A good way to determine the doneness of fish is when the flesh still looks translucent and has not become opaque?",
    options: ["True", "False"],
    correct: 1,
    hint: "Done fish changes appearance.",
    explanation: "False — properly cooked fish turns opaque; translucent flesh is undercooked.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3084,
    question: "A dressed fish is one that has had removed:",
    options: ["Gills and fins", "Viscera", "Scales", "all of the above"],
    correct: 3,
    hint: "More is removed than for a drawn fish.",
    explanation: "A dressed fish has had its viscera, scales, gills, and fins all removed.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3085,
    question: "King crab are found in what body of water?",
    options: ["Atlantic", "Pacific", "Gulf of Mexico", "Bering Sea"],
    correct: 3,
    hint: "Cold northern waters near Alaska.",
    explanation: "King crab are found in the Bering Sea.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3086,
    question: "Shrimp are graded by:",
    options: ["weight", "color", "size", "smell"],
    correct: 2,
    hint: "Think \"count per pound.\"",
    explanation: "Shrimp are graded by size (count per pound).",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3087,
    question: "Atlantic hard shell clams are known as:",
    options: ["Belly clams", "chopped clams", "Quahogs", "Goeducks"],
    correct: 2,
    hint: "A Native American name.",
    explanation: "Atlantic hard shell clams are known as quahogs.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3088,
    question: "The three types of mollusks are:",
    options: ["Univalves, snails and conchs", "Univalves, bivalves, cephalopods", "Univalves, cephalopods, Octopus", "Univalves, bivalves, spiny lobsters"],
    correct: 1,
    hint: "One shell, two shells, and the \"head-foot\" group.",
    explanation: "The three types of mollusks are univalves, bivalves, and cephalopods.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3089,
    question: "Fish are high in a group of polyunsaturated fatty acids called?",
    options: ["Cholesterol", "High density lipids", "Omega-3", "Mercury"],
    correct: 2,
    hint: "Heart-healthy fatty acids.",
    explanation: "Fish are high in omega-3 polyunsaturated fatty acids.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3090,
    question: "There are how many market forms of fish?",
    options: ["4", "12", "7", "6"],
    correct: 2,
    hint: "Whole, drawn, dressed, steaks, fillets, butterflied, sticks/tranche…",
    explanation: "There are 7 market forms of fish.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3091,
    question: "An example of a cephalopod is a:",
    options: ["mussel", "squid", "oyster", "clam"],
    correct: 1,
    hint: "Has tentacles, no external shell.",
    explanation: "A squid is a cephalopod; mussels, oysters, and clams are bivalves.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3092,
    question: "To determine the freshness in fish, the 6 areas we inspect are: smell, eyes, gills, texture, fins/scales, appearance.",
    options: ["True", "False"],
    correct: 0,
    hint: "All six are sensory checks.",
    explanation: "True — freshness is judged by smell, eyes, gills, texture, fins/scales, and appearance.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3093,
    question: "Seafood is inherently tender?",
    options: ["True", "False"],
    correct: 0,
    hint: "It has little connective tissue.",
    explanation: "True — seafood has little connective tissue, so it is naturally tender and cooks quickly.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },
  {
    id: 3094,
    question: "What type of market fish is dipped into chilled water to form a protective layer of ice?",
    options: ["Fancy", "Chilled", "Glazed", "Fresh"],
    correct: 2,
    hint: "The ice coating gives it its name.",
    explanation: "Glazed fish is dipped in chilled water to form a protective ice layer, preventing freezer burn.",
    category: "Fish & Shellfish",
    topic: "Fish & Shellfish",
    chapter: 4,
    examFocus: true,
    type: "quiz"
  },

  // ===== FLASHCARDS: CLASSICAL COOKING VOCABULARY (VOCABULARY.pdf) =====
  {
    id: 4001,
    question: "Clarified butter",
    options: ["Butter from which the milk solids and water have been removed, so that only the butterfat remains."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Clarified butter is butter with the milk solids and water removed, leaving only butterfat (a higher smoke point).",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Clarified butter",
    flashBack: "Butter from which the milk solids and water have been removed, so that only the butterfat remains.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4002,
    question: "Fond",
    options: ["The flavorful solid bits of food stuck to a pan after cooking; deglazed with liquid to make a stock, broth, or sauce."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Fond refers to the browned bits left in the pan after cooking, which are deglazed to build flavor.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Fond",
    flashBack: "The flavorful solid bits of food stuck to a pan after cooking; deglazed with liquid to make a stock, broth, or sauce.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4003,
    question: "Au sec",
    options: ["A liquid that has been reduced until it is nearly dry. (\"nearly dry\" in French)"],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Au sec means a liquid reduced until nearly dry.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Au sec",
    flashBack: "A liquid that has been reduced until it is nearly dry. (\"nearly dry\" in French)",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4004,
    question: "Deglaze",
    options: ["Adding liquid to a hot pan to dissolve the browned food particles (fond) stuck to the bottom and sides."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Deglazing dissolves the fond with liquid to capture its flavor for a sauce.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Deglaze",
    flashBack: "Adding liquid to a hot pan to dissolve the browned food particles (fond) stuck to the bottom and sides.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4005,
    question: "Depouillage",
    options: ["The process of skimming the foam or scum from a stock, broth, or sauce."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Depouillage is skimming the impurities (foam/scum) from the surface of a simmering stock or sauce.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Depouillage",
    flashBack: "The process of skimming the foam or scum from a stock, broth, or sauce.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4006,
    question: "Remouillage",
    options: ["Rewetting used stock bones to make a second, lighter stock; can be used as the liquid for new stocks."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Remouillage (\"rewetting\") makes a second stock from already-used bones.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Remouillage",
    flashBack: "Rewetting used stock bones to make a second, lighter stock; can be used as the liquid for new stocks.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4007,
    question: "Caramelize",
    options: ["To convert sugars with heat to develop the characteristic brown color and nutty flavor of caramel; also adds color to dishes."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Caramelizing browns sugars with heat to develop color and nutty flavor.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Caramelize",
    flashBack: "To convert sugars with heat to develop the characteristic brown color and nutty flavor of caramel; also adds color to dishes.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4008,
    question: "Roux",
    options: ["A cooked mixture of flour and fat used as a thickening agent in a soup or sauce."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "A roux is cooked flour and fat used to thicken sauces and soups.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Roux",
    flashBack: "A cooked mixture of flour and fat used as a thickening agent in a soup or sauce.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4009,
    question: "Glace (Glaze)",
    options: ["A dramatically reduced stock."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "A glace is a stock reduced dramatically to concentrate flavor and body.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Glace (Glaze)",
    flashBack: "A dramatically reduced stock.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4010,
    question: "Compound butter",
    options: ["Whole butter mixed with other ingredients to create or accompany a protein, usually grilled."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Compound butter is whole butter blended with flavorings, often served on grilled proteins.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Compound butter",
    flashBack: "Whole butter mixed with other ingredients to create or accompany a protein, usually grilled.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4011,
    question: "Roasting",
    options: ["Cooking something in an oven; considered a dry-heat method."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Roasting is a dry-heat cooking method done in an oven.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Roasting",
    flashBack: "Cooking something in an oven; considered a dry-heat method.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4012,
    question: "Sauté",
    options: ["Literally \"to jump.\" A dry-heat method cooking ingredients in a small amount of fat while tossing them around."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Sauté (\"to jump\") cooks food quickly in a little fat over high heat while tossing.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Sauté",
    flashBack: "Literally \"to jump.\" A dry-heat method cooking ingredients in a small amount of fat while tossing them around.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4013,
    question: "Braising",
    options: ["A method using both moist and dry heat to cook tougher proteins with more connective tissue until tender; similar to stewing but with less liquid."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Braising combines dry heat (searing) and moist heat (simmering in liquid) to tenderize tough cuts.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Braising",
    flashBack: "A method using both moist and dry heat to cook tougher proteins with more connective tissue until tender; similar to stewing but with less liquid.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4014,
    question: "Pan-frying",
    options: ["Cooking a usually breaded, tenderized tougher cut in more oil than sautéing — fat comes up about halfway, not submerged."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Pan-frying uses moderate oil (about half the depth of the food) and is often used for breaded items.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Pan-frying",
    flashBack: "Cooking a usually breaded, tenderized tougher cut in more oil than sautéing — fat comes up about halfway, not submerged.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4015,
    question: "Shallow poaching",
    options: ["Gently cooking food in liquid below boiling (140-180°F); liquid comes up only about 1/3 the depth of the protein."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Shallow poaching cooks food gently at 140-180°F in liquid that covers only about a third of the item.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Shallow poaching",
    flashBack: "Gently cooking food in liquid below boiling (140-180°F); liquid comes up only about 1/3 the depth of the protein.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4016,
    question: "Searing",
    options: ["Cooking the surface of food at high temperature to create a browned crust (Maillard reaction)."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Searing browns the surface of food at high heat via the Maillard reaction.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Searing",
    flashBack: "Cooking the surface of food at high temperature to create a browned crust (Maillard reaction).",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4017,
    question: "Flambé",
    options: ["French for \"flame.\" Igniting a dish to burn off alcohol while retaining the liquor's flavor."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Flambé ignites added alcohol to reduce its content while keeping flavor.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Flambé",
    flashBack: "French for \"flame.\" Igniting a dish to burn off alcohol while retaining the liquor's flavor.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4018,
    question: "Grilling",
    options: ["A dry-heat method cooking food directly over a heat source, usually on a metal grate, for a smoky, charred flavor."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Grilling cooks food over direct heat on a grate, producing char and smoky flavor.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Grilling",
    flashBack: "A dry-heat method cooking food directly over a heat source, usually on a metal grate, for a smoky, charred flavor.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4019,
    question: "Standard breading procedure",
    options: ["A three-step process for coating food in flour, egg, and breadcrumbs before frying or pan-frying."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "The standard breading procedure is flour → egg wash → breadcrumbs, in that order.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Standard breading procedure",
    flashBack: "A three-step process for coating food in flour, egg, and breadcrumbs before frying or pan-frying.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4020,
    question: "Cartouche",
    options: ["A parchment-paper lid (false lid) used to cover an item while poaching or stewing, or to keep a skin from forming on a sauce."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "A cartouche is a parchment lid that controls evaporation and prevents skin formation.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Cartouche",
    flashBack: "A parchment-paper lid (false lid) used to cover an item while poaching or stewing, or to keep a skin from forming on a sauce.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4021,
    question: "Supreme (airline) breast of chicken",
    options: ["A cut of chicken that includes the breast and the first wing joint (drumette), often prepared skin-on."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "An airline/supreme breast is a chicken breast with the first wing joint attached.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Supreme (airline) breast of chicken",
    flashBack: "A cut of chicken that includes the breast and the first wing joint (drumette), often prepared skin-on.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4022,
    question: "Paupiette",
    options: ["A long, thin slice of fish or meat, rolled and usually stuffed with a filling."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "A paupiette is a thin slice of meat or fish rolled around a filling.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Paupiette",
    flashBack: "A long, thin slice of fish or meat, rolled and usually stuffed with a filling.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  },
  {
    id: 4023,
    question: "Scaloppini",
    options: ["A thinly sliced cut of meat (usually veal, beef, or chicken) dredged in flour and sautéed; served with an appropriate sauce, vegetables, or pasta."],
    correct: 0,
    hint: "Tap to reveal the definition",
    explanation: "Scaloppini are thin slices of meat, floured and sautéed, served with a sauce.",
    category: "Culinary Terms",
    topic: "Culinary Vocabulary",
    flashFront: "Scaloppini",
    flashBack: "A thinly sliced cut of meat (usually veal, beef, or chicken) dredged in flour and sautéed; served with an appropriate sauce, vegetables, or pasta.",
    chapter: null,
    examFocus: false,
    type: "flashcard"
  }
];
